app/mod_api/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, Response, request, render_template
import json
from app import data_manager_kb, data_manager_ljp

mod_api = Blueprint('api', __name__, url_prefix='/api')

@mod_api.route("/grafikona/konsolidovani-budzet/", methods=['POST'])
def konsolidovani_budzet():
    '''
        Retrieves revenues and expenditures data.
        Filter based on values given in POST body.
    '''

    json_data = request.data
    json_obj = json.loads(json_data)
    result = data_manager_kb.get_chart_data(json_obj)

    return Response(response=json.dumps(result), status=200, mimetype='application/json')


@mod_api.route("/grafikona/lokalna-javna-produzeca", methods=['POST'])
def lokalna_javna_produzeca():
    '''
        Retrieves public companies data.
        Filter based on values given in POST body.
    '''

    json_data = request.data
    json_obj = json.loads(json_data)
    result = data_manager_ljp.get_chart_data(json_obj)

    # Return JSON response based on filtering parameters we gave in post request body
    return Response(response=json.dumps(result), status=200, mimetype='application/json')


@mod_api.route("/", methods=['GET'])
def index():
    '''
    Renders the API documentation page.
    :return:
    '''
    return render_template('mod_api/index.html')

@mod_api.route("/konsolidovani-budzet", methods=['POST'])
def get_raw_konsolidovani_budzet():
    ''' Fetches documents for konsolidovani budzet.
    :return:
    '''

    query_obj = json.loads(request.data)
    result = data_manager_kb.get_chart_data(query_obj)

    return Response(response=result, status=200, mimetype='application/json')

@mod_api.route("/lokalna-javna-produzeca", methods=['POST'])
def get_raw_lokalna_javna_produzeca():
    ''' Fetches documents for lokalna javna produzeca.
    :return:
    '''
    query_obj = json.loads(request.data)
    result = data_manager_ljp.get_chart_data(query_obj)

    return Response(response=result, status=200, mimetype='application/json')

app/templates/mod_api/index.html
{% extends "layout.html" %}
{% block body %}
    <div class="container" style="padding-top:40px;">
        <h1>Data API</h1>
        API se sastoji od dva POST zahteva: jedan za preuzimanje podataka iz dela <strong> finansijski izveštaji (konsolidovani budžet) </strong>, a drugi za preuzimanje podataka za <strong>lokalna javna preduzeća</strong>.
        Svaki POST zahtev prima telo poruke JSON objekta u kome možete da definišete opcione parametre upita.  Koristite ove parametre za filtriranje dobijenih podataka.
        <br><br>
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">FINANSIJSKI IZVEŠTAJI (KONSOLIDOVANI BUDŽET)</h3>
            </div>
            <div class="panel-body">
                <h4>OPIS:</h4>
                Koristite ovaj POST zahtev za preuzimanje podataka o prihodima i rashodima iz dela <strong>Finansijski izveštaji</strong>.

                <br><br>

                <h4>URL POST ZAHTEVA:</h4>
                {{ config.HOST }}{{ url_for('api.get_raw_konsolidovani_budzet') }}
                <br><br>
                <h4>PARAMETRI UPITA:</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Parameter
                            </th>
                            <th>
                                Vrsta
                            </th>
                            <th>
                                Opis
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>
                                godine
                            </th>
                            <td>
                                Lista celih brojeva
                            </td>
                            <td>
                                Godine za koje želimo da preuzmemo podatke o prihodima/rashodima.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                prihodRashod
                            </th>
                            <td>
                                String
                            </td>
                            <td>
                                Pokazuje da li želimo podatke o prihodima ili rashodima.<br>
                                Izbor: prihodi ili rashodi.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                opstina
                            </th>
                            <td>
                                Lista stringova
                            </td>
                            <td>
                                Opštine za koje želimo da preuzmemo podatke o prihodima/rashodima.
                            </td>
                        </tr>

                        <tr>
                            <th>
                                konta
                            </th>
                            <td>
                                Lista celih brojeva
                            </td>
                            <td>
                                Identifikacioni brojevi računa.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                sort
                            </th>
                            <td>
                                String
                            </td>
                            <td>
                                Pokazuje koje parametre koristimo za sortiranje podataka.<br>
                                Izbori: godine, prihodRashod, opstina, ili konta.
                            </td>
                        </tr>
                    </tbody>
                </table>
                <h5>PRIMER PARAMETRA UPITA ZA TELO PORUKE JSON OBJEKTA:</h5>
                <pre>
                    <code class="language-css">
            {
                "godine": [
                    2006
                ],
                "prihodRashod": "rashodi",
                "opstina": [
                    "Šid"
                ],
                "konta": [
                    612
                ],
                "sort": "opstina"
            }

                    </code>
                </pre>

            </div>
        </div>

        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Lokalna javna preduzeća</h3>
            </div>
            <div class="panel-body">
                <h4>OPIS:</h4>
                Koristite ovaj POST zahtev za preuzimanje podataka o rashodima za <strong>Lokalna javna preduzeća</strong>.
                <br><br>

                <h4>PARAMETRI UPITA:</h4>
                {{ config.HOST }}{{ url_for('api.get_raw_lokalna_javna_produzeca') }}
                <br><br>

                <h4>Query Parameters:</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Parameter
                            </th>
                            <th>
                                Vrsta
                            </th>
                            <th>
                                Opis
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th>
                                godine
                            </th>
                            <td>
                                Lista celih brojeva
                            </td>
                            <td>
                                Godine kada su se aktivnosti odigrale.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                delatnost
                            </th>
                            <td>
                                Lista celih brojeva
                            </td>
                            <td>
                                Identifikacioni broj aktivnosti.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                opstina
                            </th>
                            <td>
                                Lista stringova
                            </td>
                            <td>
                                Opštine u kojima su se odigrale aktivnosti.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                preduzece
                            </th>
                            <td>
                                Lista celih brojeva
                            </td>
                            <td>
                                Identifikacioni broj preduzeća uključenih u aktivnosti.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                osnivaci
                            </th>
                            <td>
                                Lista stringova
                            </td>
                            <td>
                                Nazivi osnivača preduzeća.
                            </td>
                        </tr>
                        <tr>
                            <th>
                                sort
                            </th>
                            <td>
                                String
                            </td>
                            <td>
                                Pokazuje koje parametre koristimo za sortiranje podataka.<br>
                                Izbor: godine, delatnost, opstina, preduzeca, ili osnivaci.
                            </td>
                        </tr>
                    </tbody>
                </table>
                <h5>PRIMER PARAMETRA UPITA ZA TELO PORUKE JSON OBJEKTA:</h5>
                <pre>
                    <code class="language-css">

            {
                "godine": [
                    2010
                ],
                "delatnost": [
                    6311
                ],
                "opstina": [
                    "vozdovac"
                ],
                "preduzece": [
                    7048971
                ],
                "osnivaci": "skupstina-grada-beograda-beograd-dragoslava-jovanovica-2",
                "sort": "godine"
            }
                    </code>
                </pre>
            </div>
        </div>
    </div>


{% endblock %}