app/mod_admin/forms/form.py
# coding=utf-8
from wtforms import Form, StringField, PasswordField, TextAreaField, TextField, validators, HiddenField, SelectField
from wtforms.validators import Required

class AdminForm(Form):
    username = StringField('Username', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])

    title = TextField('Title', [validators.required(), validators.length(max=10)])
    chart_type = SelectField('Tip grafikona', choices=[('Barchart', 'Barchart'),('Floating Bubbles', 'Floating Bubbles'),('Map', 'Mapa'),('Scatterplot', 'Scatterplot')])
    description = TextAreaField('Description', [validators.optional(), validators.length(max=200)])
    share_link = TextField('Share Link', [validators.required(), validators.length(max=10)])
    chart_id = HiddenField('Chart ID')

app/mod_admin/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, redirect, current_app, session, url_for
from flask.ext.scrypt import check_password_hash
from bson import ObjectId
from app.mod_admin.forms.form import AdminForm
from app import mongo

mod_admin = Blueprint('admin', __name__)

@mod_admin.route('/admin/panel', methods=['GET'])
def panel():
    if 'logged_in' in session:
        form = AdminForm()

        charts_doc = list(mongo.db.charts.find())
        return render_template('mod_admin/admin_panel.html', form=form, charts_doc=charts_doc)
    else:
        return redirect(url_for('admin.login'))

@mod_admin.route('/odabrani-grafikoni', methods=['GET'])
def featured_charts():

    charts_doc = list(mongo.db.charts.find())

    return render_template('mod_admin/featured-charts.html', charts_doc=charts_doc)

@mod_admin.route('/admin/add-chart', methods=['POST'])
def addchart():

    form = AdminForm(request.form)

    chart_doc = {
        "title": form.title.data,
        "chart_type": form.chart_type.data,
        "description": form.description.data,
        "share_link": form.share_link.data
    }
    mongo.db.charts.insert(chart_doc)
    return redirect(url_for('admin.panel'))

@mod_admin.route('/admin/edit-chart', methods=['POST'])
def editchart():
    form = AdminForm(request.form)

    chart_id = form.chart_id.data
    edited_doc = {
        "title": form.title.data,
        "chart_type": form.chart_type.data,
        "description": form.description.data,
        "share_link": form.share_link.data
    }

    mongo.db.charts.update(
        {"_id": ObjectId(chart_id)},
        {
            "$set": edited_doc
        }
    )

    return redirect(url_for('admin.panel'))

@mod_admin.route('/admin/delete-chart/<string:chart_id>', methods=['GET'])
def delete_chart(chart_id):

    mongo.db.charts.remove({"_id": ObjectId(chart_id)})

    return redirect(url_for('admin.panel'))



@mod_admin.route('/admin/log-in', methods=['GET', 'POST'])
def login():
    error = None
    form = AdminForm(request.form)

    if request.method == "POST":

        username = form.username.data
        password = form.password.data
        user_doc = mongo.db.users.find_one({"username": username})

        if user_doc is None:
            error = "Korisnik ne postoji"
        elif password == "" or not check_password_hash(password, user_doc["password"], user_doc["salt"]):
            error = "Pogrešna lozinka"

        else:
            session['logged_in'] = True
            session['username'] = username
            return redirect(url_for('admin.panel'))

        return render_template('mod_admin/login_form.html', form=form, error=error)

    elif request.method == "GET":

        return render_template('mod_admin/login_form.html', form=form, error=error)


@mod_admin.route('/admin/log-out', methods=['GET'])
def logout():
    if 'logged_in' in session and session['logged_in'] is True:
        session.pop('logged_in', None)

        username = session['username']
        session.pop('username', None)

        current_app.logger.info('user %s is logged out' % username)

        return redirect(url_for('landing_page.index'))

    else:
        return redirect(url_for('admin.login'))

app/templates/mod_admin/admin_panel.html
{% extends "layout.html" %}
{% block style %}
<style type="text/css">

td {
    /* css-3 */
    word-wrap: break-word;

}
table {
  table-layout: fixed;
  width: 100%
}
</style>

{% endblock %}
{% block script %}
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function(){
         $(".updateit").click(function(){
              var tr_id = $(this).attr('id');
              var data_array = []
             $("td", "#"+ tr_id).each(function(){
                data_array.push($(this).text());
             });
             console.log(data_array);
             $('#chart_id', "#myModalEdit").val(tr_id);
             $('#title', "#myModalEdit").val(data_array[0]);
             $('#chart_type', "#myModalEdit").val(data_array[1]);
             $('#description', "#myModalEdit").val(data_array[2]);
             $('#share_link', "#myModalEdit").val(data_array[3]);
         });
    });
    </script>
{% endblock %}
{% block body %}

    <div class="container" style="margin-top: 100px">


        <div class="panel panel-primary">
            <div class="panel-heading">Koristite ovu tabelu za upravaljanje predefinisanim grafikonima.
            </div>
            <div class="panel-body ">

                <button type="button" class="btn btn-sm btn-default col-xs-offset-5 col-xs-2" data-toggle="modal" data-target="#myModal">Dodaj</button>
            </div>
            <div class="table-responsive col-">
                <table class="table table-bordered table-stripped">
                    <thead>
                        <tr>
                            <th>Naslov</th>
                            <th>Tip grafikona</th>
                            <th>Opis</th>
                            <th>Share link</th>
                            <th class="col-xs-1">Operacije</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if charts_doc is defined and charts_doc|length > 0 %}
                        {% for doc in charts_doc %}
                        <tr id ="{{doc._id}}">
                            <td >{{ doc.title }}</td>
                            <td>{{ doc.chart_type }}</td>
                            <td>{{ doc.description }}</td>
                            <td><a href="{{ doc.share_link }}" style="color:darkred !important;"> {{ doc.share_link }}</a></td>
                            <td class="col-xs-1">
                                <div class="row" style="margin-left: 5px;">
                                    <div class="col-xs-5" style="padding-left: 1px;padding-right: 0;">
                                        <button type="button" data-toggle="modal" data-target="#myModalEdit" class="updateit btn btn-sm btn-default pull-right" id="{{ doc._id }}"><i class="glyphicon glyphicon-edit"></i></button>
                                    </div>
                                    <div class="col-xs-5 pull-left" style="padding-left: 1px;">
                                        <form method='get' action="{{url_for('admin.delete_chart', chart_id=doc._id) }}">
                                            <button type="submit" class="delete btn btn-sm btn-default" id ="{{ doc._id }}"><i class="glyphicon glyphicon-remove"></i></button>
                                        </form>
                                    </div>
                                </div>


                            </td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
<div id="myModal" class="modal fade " data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-info">Odabrani grafikoni!</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="post" action="{{ url_for('admin.addchart') }}">
                    <div class="form-group">
                      <label for="email">Naslov:</label>
                        {{form.title(class="form-control")}}
                    </div>
                    <div class="form-group">
                      <label for="pwd">Tip grafikona:</label>
                      {{form.chart_type(class="form-control")}}
                    </div>
                    <div class="form-group">
                      <label for="pwd">Opis:</label>
                      {{form.description(class="form-control")}}
                    </div>
                    <div class="form-group">
                      <label for="pwd">Share Link:</label>
                      {{form.share_link(class="form-control")}}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Zatvori</button>
                        <button type="submit" class="btn btn-info">Pošalji</button>
                    </div>

                  </form>
            </div>
        </div>
    </div>
    </div>

<div id="myModalEdit" class="modal fade " data-backdrop="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-info">Edit!</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="post" action="{{ url_for('admin.editchart') }}">
                    {{ form.chart_id() }}
                    <div class="form-group">
                      <label for="email">Naslov:</label>
                        {{form.title(class="form-control")}}
                    </div>
                    <div class="form-group">
                      <label for="pwd">Tip grafikona:</label>
                      {{form.chart_type(class="form-control")}}
                    </div>
                    <div class="form-group">
                      <label for="pwd">Opis:</label>
                      {{form.description(class="form-control")}}
                    </div>
                    <div class="form-group">
                      <label for="pwd">Share Link:</label>
                      {{form.share_link(class="form-control")}}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Zatvori</button>
                        <button type="submit" class="btn btn-info">Edit</button>
                    </div>

                  </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

app/templates/mod_admin/featured-charts.html
{% extends "layout.html" %}
{% block style %}
<style>
td {
    /* css-3 */
    word-wrap: break-word;

}
table {
  table-layout: fixed;
  width: 100%
}
</style>

{% endblock %}
{% block body %}
    <div class="container" style="margin-top: 100px">

    {% if charts_doc is defined and charts_doc|length > 0 %}
    {% for doc in charts_doc %}

        <div class="panel panel-primary" style="">
            <div class="panel-heading">
                <div class="panel-title">{{ doc.title }}</div>
            </div>
            <div style="" class="panel-body">
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Tip grafikona</th>
                            <th>Opis</th>
                            <th>Share link</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr id ="{{doc._id}}">
                            <td>{{ doc.chart_type }}</td>
                            <td>{{ doc.description }}</td>
                            <td><a href="{{ doc.share_link }}" style="color:darkred !important;"> {{ doc.share_link }}</a></td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>
     {% endfor %}
     {% endif %}

    </div>
{% endblock %}

app/templates/mod_admin/login_form.html
{% extends "layout.html" %}
{% block body %}

<div class="container" style="margin-top: 100px">
    <div id="loginbox" class="mainbox col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-2">
    {% if error != None %}
        <div class="alert alert-danger" role="alert">{{error}}</div>
    {% endif %}

        <div class="panel panel-primary" >
            <div class="panel-heading">
                <div class="panel-title">Uloguj se</div>
                <div style="float:right; font-size: 80%; position: relative; top:-10px">Uloguj se za pristup admin delu</div>
            </div>
            <div style="padding-top:30px" class="panel-body" >

                <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                <form id="loginform" action="{{ url_for('admin.login') }}" method="post" class="form-horizontal" role="form">
                    <div style="margin-bottom: 25px" class="col-xs-offset-2 col-xs-8">
                        {{form.username(class="form-control", placeholder="Korisničko ime")}}
                    </div>
                    <div style="margin-bottom: 25px" class="col-xs-offset-2 col-xs-8">
                        {{form.password(class="form-control", placeholder="Šifra")}}
                    </div>
                    <div style="margin-bottom: 25px" class="col-xs-offset-2 col-xs-8">
                        <button type="submit" class="btn btn-success">Uloguj se</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock %}