app/mod_admin/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request, redirect, current_app, session, url_for
from flask.ext.scrypt import check_password_hash
from bson import ObjectId
from app.mod_admin.forms.form import AdminForm
from app import mongo

mod_admin = Blueprint('admin', __name__)

@mod_admin.route('/admin/panel', methods=['GET'])
def panel():
    if 'logged_in' in session:
        form = AdminForm()

        charts_doc = list(mongo.db.charts.find())
        return render_template('mod_admin/admin_panel.html', form=form, charts_doc=charts_doc)
    else:
        return redirect(url_for('admin.login'))

@mod_admin.route('/odabrani-grafikoni', methods=['GET'])
def featured_charts():

    charts_doc = list(mongo.db.charts.find())

    return render_template('mod_admin/featured-charts.html', charts_doc=charts_doc)

@mod_admin.route('/admin/add-chart', methods=['POST'])
def addchart():

    form = AdminForm(request.form)

    chart_doc = {
        "title": form.title.data,
        "chart_type": form.chart_type.data,
        "description": form.description.data,
        "share_link": form.share_link.data
    }
    mongo.db.charts.insert(chart_doc)
    return redirect(url_for('admin.panel'))

@mod_admin.route('/admin/edit-chart', methods=['POST'])
def editchart():
    form = AdminForm(request.form)

    chart_id = form.chart_id.data
    edited_doc = {
        "title": form.title.data,
        "chart_type": form.chart_type.data,
        "description": form.description.data,
        "share_link": form.share_link.data
    }

    mongo.db.charts.update(
        {"_id": ObjectId(chart_id)},
        {
            "$set": edited_doc
        }
    )

    return redirect(url_for('admin.panel'))

@mod_admin.route('/admin/delete-chart/<string:chart_id>', methods=['GET'])
def delete_chart(chart_id):

    mongo.db.charts.remove({"_id": ObjectId(chart_id)})

    return redirect(url_for('admin.panel'))



@mod_admin.route('/admin/log-in', methods=['GET', 'POST'])
def login():
    error = None
    form = AdminForm(request.form)

    if request.method == "POST":

        username = form.username.data
        password = form.password.data
        user_doc = mongo.db.users.find_one({"username": username})

        if user_doc is None:
            error = "Korisnik ne postoji"
        elif password == "" or not check_password_hash(password, user_doc["password"], user_doc["salt"]):
            error = "Pogrešna lozinka"

        else:
            session['logged_in'] = True
            session['username'] = username
            return redirect(url_for('admin.panel'))

        return render_template('mod_admin/login_form.html', form=form, error=error)

    elif request.method == "GET":

        return render_template('mod_admin/login_form.html', form=form, error=error)


@mod_admin.route('/admin/log-out', methods=['GET'])
def logout():
    if 'logged_in' in session and session['logged_in'] is True:
        session.pop('logged_in', None)

        username = session['username']
        session.pop('username', None)

        current_app.logger.info('user %s is logged out' % username)

        return redirect(url_for('landing_page.index'))

    else:
        return redirect(url_for('admin.login'))

app/mod_api/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, Response, request, render_template
import json
from app import data_manager_kb, data_manager_ljp

mod_api = Blueprint('api', __name__, url_prefix='/api')

@mod_api.route("/grafikona/konsolidovani-budzet/", methods=['POST'])
def konsolidovani_budzet():
    '''
        Retrieves revenues and expenditures data.
        Filter based on values given in POST body.
    '''

    json_data = request.data
    json_obj = json.loads(json_data)
    result = data_manager_kb.get_chart_data(json_obj)

    return Response(response=json.dumps(result), status=200, mimetype='application/json')


@mod_api.route("/grafikona/lokalna-javna-produzeca", methods=['POST'])
def lokalna_javna_produzeca():
    '''
        Retrieves public companies data.
        Filter based on values given in POST body.
    '''

    json_data = request.data
    json_obj = json.loads(json_data)
    result = data_manager_ljp.get_chart_data(json_obj)

    # Return JSON response based on filtering parameters we gave in post request body
    return Response(response=json.dumps(result), status=200, mimetype='application/json')


@mod_api.route("/", methods=['GET'])
def index():
    '''
    Renders the API documentation page.
    :return:
    '''
    return render_template('mod_api/index.html')

@mod_api.route("/konsolidovani-budzet", methods=['POST'])
def get_raw_konsolidovani_budzet():
    ''' Fetches documents for konsolidovani budzet.
    :return:
    '''

    query_obj = json.loads(request.data)
    result = data_manager_kb.get_chart_data(query_obj)

    return Response(response=result, status=200, mimetype='application/json')

@mod_api.route("/lokalna-javna-produzeca", methods=['POST'])
def get_raw_lokalna_javna_produzeca():
    ''' Fetches documents for lokalna javna produzeca.
    :return:
    '''
    query_obj = json.loads(request.data)
    result = data_manager_ljp.get_chart_data(query_obj)

    return Response(response=result, status=200, mimetype='application/json')

app/mod_konsolidovani_budzet/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, request
from urlparse import urlparse
from bson import json_util
from app.mod_konsolidovani_budzet.forms.form import RevenuesAndExpenditureForm
from app.utils.url_query_utils import UrlQueryUtils
from app import data_manager_kb
from app.mod_konsolidovani_budzet.forms.utils import FormUtils

mod_konsolidovani_budzet = Blueprint('konsolidovani_budzet', __name__, url_prefix='/finansijski-izvestaji')


@mod_konsolidovani_budzet.route('/', methods=['GET'])
def index():

    data = None
    chart_type = None
    data_series = None
    fiscal_type = None
    selected_municipalities = None
    selected_years = None
    selected_fiscal_type = None
    selected_descriptions_exp = None
    selected_descriptions_rev = None
    group_by = None
    group_by_bubble = None
    disaggregated_by = None

    tree_years = FormUtils.get_tree_years()

    tree_municipalities = FormUtils.get_tree_municipalities()

    tree_income_types = FormUtils.get_tree_income_type()

    tree_revenue_descriptions = FormUtils.get_tree_revenue_descriptions()

    tree_expenditure_descriptions = FormUtils.get_tree_expenditure_descriptions()

    url_query = urlparse(request.url).query

    if url_query != '':
        # convert url query string into into JSON doc
        query_params = UrlQueryUtils.build_bd_query_params_from_url_query(url_query)

        chart_type = query_params['chartType']
        if chart_type == 'Map':
            fiscal_type = query_params['data']['fiscalType']['map']
            data_series = query_params['data']['series']['map']

        elif chart_type == 'Barchart':
            fiscal_type = query_params['data']['fiscalType']['barchart']
            data_series = query_params['data']['series']['barchart']
            group_by = query_params['data']['groupBy']

        elif chart_type == 'Scatterplot':
            data_series = query_params['data']['series']['scatterplot']

        elif chart_type == 'Floating Bubbles':
            disaggregated_by = query_params['data']['disaggregateBy']
            group_by_bubble = query_params['data']['floatingBubblesGroupBy']
            fiscal_type = query_params['data']['fiscalType']['floatingBubbles']
            data_series = query_params['data']['series']['floatingBubbles']

        data = data_manager_kb.get_chart_data(query_params)
        selected_municipalities = query_params['filters']['municipalities']
        selected_years = query_params['filters']['years']
        selected_fiscal_type = query_params['filters']['incomeTypes']
        selected_descriptions_exp = query_params['filters']['descriptions']['expenditures']
        selected_descriptions_rev = query_params['filters']['descriptions']['revenues']


    form = RevenuesAndExpenditureForm()
    return render_template(
        'mod_konsolidovani_budzet/index.html',
        form=form,
        tree_years=json_util.dumps(tree_years),
        tree_municipalities=json_util.dumps(tree_municipalities),
        tree_income_types=json_util.dumps(tree_income_types),
        tree_revenue_descriptions=json_util.dumps(tree_revenue_descriptions),
        tree_expenditure_descriptions=json_util.dumps(tree_expenditure_descriptions),
        data=json_util.dumps(data),
        chart_type=chart_type,
        data_series=data_series,
        fiscal_type=fiscal_type,
        group_by=group_by,
        disaggregated_by=disaggregated_by,
        group_by_bubble=group_by_bubble,
        selected_municipalities=json_util.dumps(selected_municipalities),
        selected_years=json_util.dumps(selected_years),
        selected_income_type=json_util.dumps(selected_fiscal_type),
        selected_descriptions_exp=json_util.dumps(selected_descriptions_exp),
        selected_descriptions_rev=json_util.dumps(selected_descriptions_rev)
    )

app/mod_lokalna_javna_produzeca/views.py
# coding=utf-8
from flask import Blueprint, render_template, request
from urlparse import urlparse

from forms.barchart_ljp_form import BarchartLJPForm
from forms.map_ljp_form import MapLJPForm
from forms.scatterplot_ljp_form import ScatterplotLJPForm
from forms.floating_bubbles_ljp_form import FloatingBubblesLJPForm
from urlparse import parse_qsl
from bson import json_util
from app import data_manager_ljp
from app.utils.url_query_utils import UrlQueryUtils
from app.mod_lokalna_javna_produzeca.forms.utils import FormUtils

mod_lokalna_javna_produzeca = Blueprint('lokalna_javna_produzeca', __name__, url_prefix='/lokalna-javna-produzeca')

@mod_lokalna_javna_produzeca.route('/', methods=['GET'])
def index():

    data = None
    chart_type = None
    selected_municipalities = None
    selected_years = None
    selected_companies = None
    selected_activities = None
    selected_owners = None
    data_series = None
    x_series = None
    y_series = None
    categories_y = None
    categories_x = None
    categories = None
    disaggregated_by = None
    group_by_bubble = None
    selected_labels = None
    ukupni_rashodi_categories = None
    poslovni_rashodi_categories = None
    ostali_categories = None
    all_activities = None
    all_companies = None
    all_municipalities = None
    all_owners = None

    barchart_form = BarchartLJPForm()
    map_form = MapLJPForm()
    scatterplot_form = ScatterplotLJPForm()
    floating_bubbles_form = FloatingBubblesLJPForm()

    tree_years = FormUtils.get_tree_years()
    tree_municipalities = FormUtils.get_tree_municipalities()
    tree_companies = FormUtils.get_tree_companies()
    tree_owners = FormUtils.get_tree_owners()
    tree_activities = FormUtils.get_tree_activities()

    url_query = urlparse(request.url).query

    if url_query != '':

        queries = parse_qsl(url_query)
        queries_dict = {}

        # Transform the list of tuples into a dictionary.
        # We do this so we can elegantly handle optional parameters (descriptionRevenues and descriptionExpenditures).
        for query in queries:
            queries_dict[query[0]] = query[1]
        query_params = UrlQueryUtils.build_ljp_query_params_json_from_url_query(queries_dict)

        if "municipalities" in queries_dict and queries_dict['municipalities'] == "Ukupno":
            all_municipalities = True
        if "activities" in queries_dict and queries_dict['activities'] == "Ukupno":
            all_activities = True
        if "companies" in queries_dict and queries_dict['companies'] == "Ukupno":
            all_companies = True
        if "owners" in queries_dict and queries_dict['owners'] == "Ukupno":
            all_owners = True

        chart_type = query_params['tipGrafikona']
        data = data_manager_ljp.get_chart_data(query_params)
        selected_municipalities = query_params['filteri']['opstine']
        selected_years = query_params['filteri']['godine']
        selected_companies = query_params['filteri']['preduzeca']
        selected_activities = query_params['filteri']['delatnosti']
        selected_owners = query_params['filteri']['osnivaci']

        if chart_type == "Scatterplot":
            data_series = query_params['podaci']['series']
            scatterplot_form.x_axis.data = query_params['podaci']['x']['selected']
            scatterplot_form.y_axis.data = query_params['podaci']['y']['selected']
            y_series = query_params['podaci']['y']['selected']
            x_series = query_params['podaci']['x']['selected']
            categories_x = query_params['podaci']['x']['params']
            categories_y = query_params['podaci']['y']['params']

        if chart_type == "Map":
            map_form.map_data_series.data = query_params['podaci']['selected']
            data_series = query_params['podaci']['selected']
            categories = json_util.dumps(query_params['podaci']['params'])

        if chart_type == "Barchart":
            data_series = [query_params['podaci']['ukupniRashodi']['selected'], query_params['podaci']['poslovniRashodi']['selected'], query_params['podaci']['ostali']['selected']]

            barchart_form.group_by.data = query_params['podaci']['grupisanoPo']

            if query_params['podaci']['ukupniPrihodi'] is True:
                barchart_form.data_series_ukupni_prihodi.data = query_params['podaci']['ukupniPrihodi']

            if query_params['podaci']['ukupniRashodi']['selected'] is True:
                barchart_form.data_series_ukupni_rashodi.data = query_params['podaci']['ukupniRashodi']['selected']
                ukupni_rashodi_categories = json_util.dumps(query_params['podaci']['ukupniRashodi']["params"])

            if query_params['podaci']['poslovniRashodi']['selected'] is True:
                barchart_form.data_series_poslovni_rashodi.data = query_params['podaci']['poslovniRashodi']['selected']
                poslovni_rashodi_categories = json_util.dumps(query_params['podaci']['poslovniRashodi']["params"])

            if query_params['podaci']['ostali']['selected'] is True:
                barchart_form.data_series_others.data = query_params['podaci']['ostali']['selected']
                ostali_categories = json_util.dumps(query_params['podaci']['ostali']['params'])


        if chart_type == 'Floating Bubbles':
            disaggregated_by = query_params['podaci']['disaggregateBy']
            group_by_bubble = query_params['podaci']['grupisanoPo']
            floating_bubbles_form.data_series.data = query_params['podaci']['selected']
            if disaggregated_by == 'Godina':
                selected_labels = selected_years

            elif disaggregated_by == 'Preduzeća':
                selected_labels = selected_companies

            elif disaggregated_by == 'Opština':
                selected_labels = selected_municipalities

            elif disaggregated_by == 'Delatnosti':
                selected_labels = selected_activities

            elif disaggregated_by == 'Osnivači':
                selected_labels = selected_owners

    return render_template(
        'mod_lokalna_javna_produzeca/index.html',
        chart_type=chart_type,
        data=json_util.dumps(data),
        barchart_form=barchart_form,
        map_form=map_form,
        scatterplot_form=scatterplot_form,
        floating_bubbles_form=floating_bubbles_form,
        tree_years=json_util.dumps(tree_years),
        tree_municipalities=json_util.dumps(tree_municipalities),
        tree_activities=json_util.dumps(tree_activities),
        tree_companies=json_util.dumps(tree_companies),
        tree_owners=json_util.dumps(tree_owners),
        selected_municipalities=json_util.dumps(selected_municipalities),
        selected_years=json_util.dumps(selected_years),
        selected_companies=json_util.dumps(selected_companies),
        selected_activities=json_util.dumps(selected_activities),
        selected_owners=json_util.dumps(selected_owners),
        data_series=json_util.dumps(data_series),
        y_series=y_series,
        x_series=x_series,
        categories_x=json_util.dumps(categories_x),
        categories_y=json_util.dumps(categories_y),
        categories=categories,
        disaggregated_by=disaggregated_by,
        group_by_bubble=group_by_bubble,
        selected_labels=json_util.dumps(selected_labels),
        ukupni_rashodi_categories=ukupni_rashodi_categories,
        poslovni_rashodi_categories=poslovni_rashodi_categories,
        ostali_categories=ostali_categories,
        all_activities=all_activities,
        all_companies=all_companies,
        all_municipalities=all_municipalities,
        all_owners=all_owners
    )

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <!-- Meta stuff -->
      <title>CRTA Budžet.info</title>
      <meta name="description" content="Sve o budžetime vašeg grada ili opštine. Različiti gradovi imaju različite budžete. Uporedite ko koliko troši i sa koliko para poreskih obveznika (nas građana Republike Srbije) raspolaže.">
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <meta name="author" content="">

      <meta name="viewport" content="width=device-width,initial-scale=1">

      <meta charset="utf-8">

      <!-- Twitter Card data -->
      <meta name="twitter:card" content="summary">
      <meta name="twitter:site" content="@CRTArs">
      <meta name="twitter:title" content="Sve o budžetime vašeg grada ili opštine #BudžetInfo: ">
      <meta name="twitter:description" content="Sve o budžetime vašeg grada ili opštine #BudžetInfo: ">
      <meta name="twitter:creator" content="@CRTArs">
      <meta name="twitter:image" content="http://budzet.info/static/img/fiskalni-monitor-main-logo-horizontal.png">

      <!-- Open Graph data -->
      <meta property="og:title" content="Budžet.info" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="http://budzet.info/" />
      <meta property="og:image" content="http://budzet.info/static/img/fiskalni-monitor-main-logo-horizontal.png"/>
      <meta property="og:description" content="Sve o budžetime vašeg grada ili opštine." />
      <meta property="og:site_name" content="Budžet.info" />

      <!-- CSS -->
      <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/theme/bootstrap.css')}}" media="screen">

      <!-- D3 js CSS -->
      <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/theme/reset.css')}}">
      <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/theme/d3_style.css')}}">

      <!-- Own CSS -->
      <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='filter-controls/filter-controls.css') }}"/>

      <!-- jsTree -->
      <link href="{{ url_for('static', filename='jstree/themes/default/style.min.css')}}" rel="stylesheet">


      {% block style %}
      {% endblock %}
      <!-- JAVASCRIPT -->
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
        <script src="{{ url_for('static', filename='bootstrap/bootstrap/html5shiv.js')}}"></script>
        <script src="{{ url_for('static', filename='bootstrap/bootstrap/respond.min.js')}}"></script>
      <![endif]-->

      <!-- jQuery -->
      <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
      <script src="https://code.jquery.com/jquery-latest.min.js"></script>

      <!-- Highcharts -->
      <!--
      <script src="http://code.highcharts.com/maps/modules/data.js"></script>
      <script src="http://code.highcharts.com/maps/modules/exporting.js"></script>
      -->
      <script src="http://code.highcharts.com/highcharts.js"></script>
      <script src="http://code.highcharts.com/maps/modules/map.js"></script>

      <!-- Plugin JavaScript -->
      <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
      <script src="{{ url_for('static', filename='filter-controls/classie.js')}}"></script>

      <!-- Bootstrap -->
      <script src="{{ url_for('static', filename='bootstrap/bootstrap/bootstrap.js')}}"></script>

      <!-- Agency Bootstrap Theme files -->
      <script src="{{ url_for('static', filename='bootstrap/bootstrap/agency.js')}}"></script>
      <script src="{{ url_for('static', filename='bootstrap/bootstrap/cbpAnimatedHeader.js')}}"></script>

      <!-- Sidebar panel -->
      <script src="{{ url_for('static', filename='filter-controls/filter-controls.js') }}"></script>

      <!-- jstree -->
      <script src="{{ url_for('static', filename='jstree/jstree.min.js')}}"></script>

      <!-- prism -->
      <script src="{{ url_for('static', filename='prism/prism.js')}}"></script>
      <link href="{{ url_for('static', filename='prism/prism.css')}}" rel="stylesheet">

      <!-- social media share -->
      <script src="{{ url_for('static', filename='social-media-sharer/jquery.share.js') }}" ></script>
      <link href="{{ url_for('static', filename='social-media-sharer/jquery.share.css') }}" rel="stylesheet">

      <!-- Custom CSS -->
      <link href="{{ url_for('static', filename='css/agency.css')}}" rel="stylesheet">

     <!-- WaitMe -->
     <link rel="stylesheet" href="{{ url_for('static', filename='waitMe/waitMe.min.css') }}" />
     <script src="{{ url_for('static', filename='waitMe/waitMe.min.js') }}"></script>



      <!-- Custom Fonts -->
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
      <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
      <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" >

      {% block script %}
      {% endblock %}
  </head>
    <body id="page-top" class="index">
    <img src="{{ url_for('static', filename='img/fiskalnimonitor-logo.png')}}" style="height:40px; display: none;" >
    <nav class="navbar navbar-primary navbar-fixed-top" id="the-nav-bar">
      <div class="container">
        <div class="navbar-header page-scroll">
          <a href="{{url_for('landing_page.index')}}" class="navbar-brand"><img style="height:40px;" src="{{ url_for('static', filename='img/fiskalnimonitor-white-logo.png')}}">Budžet.info</a>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".collapse.navbar-collapse" style="background-color: lightgrey !important;">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar btn-danger"></span>
                    <span class="icon-bar btn-danger"></span>
                    <span class="icon-bar btn-danger"></span>
                </button>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" >
            <ul class="nav navbar-nav navbar-right">
            <li class="hidden">
                <a href="#page-top"></a>
            </li>

            <li id="navbar-item-konsolidovani-budzet">
                <a class="page-scroll" href="{{url_for('konsolidovani_budzet.index')}}">Finansijski izveštaji</a>
            </li>
            <li id="navbar-item-lokalna-javna-produzeca">
                <a class="page-scroll" href="{{url_for('lokalna_javna_produzeca.index')}}">Lokalna javna preduzeća</a>
            </li>

            <li id="navbar-item-api">
              <a class="page-scroll" href="{{url_for('admin.featured_charts')}}">Odabrani grafikoni</a>
            </li>

            <li id="navbar-item-api">
                <a class="page-scroll" href="{{url_for('api.index')}}">API</a>
            </li>
            {% if session.logged_in is defined %}
            <li>
                 <a class="page-scroll" href="{{url_for('admin.panel')}}">Panel</a>
            </li>
            {% endif %}
            <li id="navbar-item-admin">
                {% if session.logged_in is not defined %}
                <a class="page-scroll" href="{{url_for('admin.login')}}">Uloguj se</a>
                {% else %}
                <a class="page-scroll" href="{{url_for('admin.logout')}}">I Logue se</a>
                {% endif %}
            </li>

    		</ul>
        </div>
      </div>
    </nav>

    {% block body %}
    {% endblock %}
  </body>
</html>